version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
  
  go-rate-limiter:
    build:
      context: .
    container_name: go-rate-limiter
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis